### ISSUE TITLE
[1.9] Crash at server start

### ISSUE THREAD

**Issue by kwpugh** [Darkhax-Minecraft/Enchanting-Plus#25]
Using Forge 1865
Mod: EnchantingPlus-1.9-4.1.0.86.jar

Crash Report: http://pastebin.com/raw/Rhg5gCBL

**Comment by ArMoReDfUrY** [comment]
I'm getting the same issue on SSP

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.item.crafting.CraftingManager.func_77596_b(SourceFile:1213)
	at net.minecraftforge.fml.common.registry.GameRegistry.addShapelessRecipe(GameRegistry.java:228)
	at net.darkhax.eplus.handler.ContentHandler.initRecipes(ContentHandler.java:130)
	at net.darkhax.eplus.EnchantingPlus.preInit(EnchantingPlus.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

MC 1.9 forge 1865
EnchantingPlus-1.9-4.1.0.8
Bookshelf-1.9-1.2.0.229

**Comment by darkhax** [comment]
Thank you for reporting the issue, it will be fixed in the next release. Just a heads up though, the jump from 1.7.10 to 1.9 is extremely huge, so E+ is missing a lot of content. At this time it only has a single item, and anything close to full functionality shouldn't be expected for a while.

**Comment by kwpugh** [comment]
Good to know.   This mod is sorely missed in 1.9.
