### ISSUE TITLE
Not working 1.10.2

### ISSUE THREAD

**Issue by bunnypig** [Darkhax-Minecraft/Enchanting-Plus#43]
The plugin isn't starting with version 1.10.2. I get this log;

[14:48:21] [Server thread/ERROR]: Could not load 'plugins\Bookshelf-1.10.2-1.4.1.319.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[craftbukkit.jar:git-Bukkit-48b88ed]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [craftbukkit.jar:git-Bukkit-48b88ed]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:295) [craftbukkit.jar:git-Bukkit-48b88ed]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.<init>(CraftServer.java:257) [craftbukkit.jar:git-Bukkit-48b88ed]
	at net.minecraft.server.v1_10_R1.PlayerList.<init>(PlayerList.java:70) [craftbukkit.jar:git-Bukkit-48b88ed]
	at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-48b88ed]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:184) [craftbukkit.jar:git-Bukkit-48b88ed]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:514) [craftbukkit.jar:git-Bukkit-48b88ed]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 9 more

[14:48:21] [Server thread/ERROR]: Could not load 'plugins\EnchantingPlus-1.10.2-4.1.0.104.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[craftbukkit.jar:git-Bukkit-48b88ed]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [craftbukkit.jar:git-Bukkit-48b88ed]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:295) [craftbukkit.jar:git-Bukkit-48b88ed]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.<init>(CraftServer.java:257) [craftbukkit.jar:git-Bukkit-48b88ed]
	at net.minecraft.server.v1_10_R1.PlayerList.<init>(PlayerList.java:70) [craftbukkit.jar:git-Bukkit-48b88ed]
	at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-48b88ed]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:184) [craftbukkit.jar:git-Bukkit-48b88ed]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:514) [craftbukkit.jar:git-Bukkit-48b88ed]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 9 more

[latest.txt](https://github.com/Darkhax-Minecraft/Enchanting-Plus/files/487273/latest.txt)

Hope it can be to some kind of help! Thanks in advance.

**Comment by darkhax** [comment]
Enchanting Plus is not a bukkit plugin and has no support for bukkit.
