### ISSUE TITLE
When I trying to learn a scroll the server kicks me out.

### ISSUE THREAD

**Issue by GamerbyDesign** [Darkhax-Minecraft/Enchanting-Plus#60]
Minecraft Client kicks me off of server when I try to learn a scroll.   This happens on two of my PC's when trying to learn a scroll.  Both PC's are running Minecraft 10.2 with Forge 12.18.3.2219.

**Comment by GamerbyDesign** [comment]
Update to EnchantingPlus 4.1.0.116 from EnchantingPlus 4.1.0.115 and the issue persists.

**Comment by GamerbyDesign** [comment]
Anything on this?

**Comment by darkhax** [comment]
Thanks for reporting the issue. I plan to fix this, and many other bugs soon. Just added this mod to my personal server, so the pressure is definitely on to make sure this mod is as stable as everyone deserves.

**Comment by GamerbyDesign** [comment]
Thank you sorry I can't give you any better info but there is no crash on client or server it just kicks me off the server.

**Comment by GamerbyDesign** [comment]
Any testing I can do to help let me know.

**Comment by staghr** [comment]
I get the same issue but with Forge 12.18.3.2185
Not sure if it helps but heres what the server says:

[20:43:12] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:19430
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
        at net.darkhax.eplus.item.ItemScroll.onUsingTick(ItemScroll.java:97) ~[ItemScroll.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2496) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1933) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at net.darkhax.eplus.item.ItemScroll.onUsingTick(ItemScroll.java:97) ~[ItemScroll.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2496) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1933) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
        ... 9 more
Caused by: java.lang.NullPointerException

**Comment by GamerbyDesign** [comment]
I can confirm that on 4.1.0.118 this issue is gone.
